assets: /home/stargazer/.cache/libero/assets
bddl_files: /home/stargazer/miniconda3/envs/vf0s/lib/python3.12/site-packages/libero/libero/bddl_files
benchmark_root: /home/stargazer/miniconda3/envs/vf0s/lib/python3.12/site-packages/libero/libero
datasets: /home/stargazer/Desktop/vla_wm/datasets/libero
init_states: /home/stargazer/miniconda3/envs/vf0s/lib/python3.12/site-packages/libero/libero/init_files
